### ISSUE TITLE
Parsing nonstring data

### ISSUE THREAD

**Issue by jtrakk** [gkappler/CombinedParsers.jl#19]
Sometimes I want to parse nonstring data, but I don't think that's allowed currently.

```jl
using CombinedParsers

parse(parser('a'), ['a']) # 'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

parse(parser(1), [1])

# ERROR: LoadError: MethodError: no method matching _iterate(::Int64, ::Array{Int64,1}, ::Int64, ::Int64, ::Int64, ::Nothing, ::Int64)
# Closest candidates are:
#   _iterate(::CombinedParsers.Regexp.WithOptions{Char}, ::Any, ::Any, ::Any, ::Any, ::Nothing, ::Any)
#   _iterate(::Char, ::Any, ::Any, ::Any, ::Any, ::Nothing, ::Any)
#   _iterate(::AbstractString, ::Any, ::Any, ::Any, ::Any, ::Nothing, ::Any)
#   ...

```

ParserCombinator.jl says 

> It can parse any iterable type (not just strings)

but I heard that package is mostly unmaintained.

**Comment by gkappler** [comment]
Parsing arbitrary sequences is possible, but syntax is not yet fully consistent. Sorry.

With your version, you can achive the result with.
```julia
parse(CharIn(1), [1])
```

Version 1.7 fixes your example.
Apologies for slow maintainance in the last months that have been very busy.
