### ISSUE TITLE
On "Example: rational numbers arithmetics"

### ISSUE THREAD

**Issue by fingolfin** [gkappler/CombinedParsers.jl#2]
I just learned about this package in the list of Juliacon talks, and wanted to have a look, as it sounds really cool. Unfortunately, I didn't quite understand the example in the README named in the title of this issue.; so I am somewhat relieved to see that Julia apparently also doesn't understand it ;-).

Indeed <https://gkappler.github.io/CombinedParsers.jl/dev/> contains this right now:

```
julia> result_type(term)
ERROR: UndefVarError: term not defined

julia> term"(1+2)/5"
ERROR: LoadError: UndefVarError: @term_str not defined
in expression starting at none:1

julia> # The defined `CombinedParser` `term` function
       # provides optional logging of the parsing process.
       term("1/((1+2)*4+3*(5*2))",log = [:parenthesis])
ERROR: UndefVarError: term not defined
```

(Personally, I never use Documenter's `@repl` anymore, instead only `jldoctest`, which IMHO has two advantages: 1. it makes it easy to read the examples in the raw Markdown; 2. it serves as "free" extra test; if something changes in your output, you normally want to know it (even though that of course adds some extra work if the change is intentional).

I also cannot get it to work locally in Julia 1.4.2:
```
julia> using CombinedParsers
[ Info: Precompiling CombinedParsers [5ae71ed2-6f8a-4ed1-b94f-e14e8158f19e]

julia> using TextParse

julia> @syntax subterm = Either{Rational{Int}}(TextParse.Numeric(Int));
ERROR: TypeError: in Tuple, in parameter, expected Type, got Tuple{DataType}
Stacktrace:
 [1] either_state_type at /Users/mhorn/.julia/packages/CombinedParsers/ZtE2s/src/CombinedParsers.jl:2352 [inlined]
 [2] Either{Rational{Int64},S,T} where T where S(::TextParse.Numeric{Int64}) at /Users/mhorn/.julia/packages/CombinedParsers/ZtE2s/src/CombinedParsers.jl:2293
 [3] top-level scope at /Users/mhorn/.julia/packages/CombinedParsers/ZtE2s/src/CombinedParsers.jl:1073
```

**Comment by gkappler** [comment]
Thanks and sorry for that syntax confusion (and the delay). I fixed the example line (This should work on your side too)
```julia
@syntax subterm = Either{Rational{Int}}(Any[TextParse.Numeric(Int)]);
```
```julia
# from old syntax:  @syntax subterm = Either{Rational{Int}}(TextParse.Numeric(Int));
```
The syntax for `Either` has changed a bit back and forth lately. Either plays a major part building recursive parsers, and comes in a Vector (mutable) and a tuple version (fast generated functions).

Here in the example, the syntax for `subterm` is `Either` a `TextParse.Numeric` or some
sub-parser that is added later. The Vector `[` syntax makes the appendability more explicit, IMO. I highly appreciate your opinion.

If I can explain clearer to help you figure out the example ;-), any hints welcome.  I like it as simple as possible. :-)

I am indeed still figuring out Documenter et al. The (full) example is a Literate processed before Documenter, with a `codefence = "```@repl session" => "```"`. Currently I am highly pleased with Franklin. The jldoctest is a good idea anyway - although it gave me a lot of false positives too and thus pattern pain. Documenter needs cleanup...

**Comment by fingolfin** [comment]
Thanks, that's better. I noticed some more issues in the manual, though:
- some links are broken, e.g. on https://gkappler.github.io/CombinedParsers.jl/dev/man/example-arithmetics/ it says after the first code block "The function definition is detailed in the full example." where the last part is a link to <https://gkappler.github.io/CombinedParsers.jl/dev/man/example-arithmetics/man/man/example-arithmetic.md> which gives 404 error.
- a few lines later there is a link to a "user guide" which is similarly broken
- in <https://gkappler.github.io/CombinedParsers.jl/dev/lib/public/#Base.get> one can see triple backquotes followed by `jldoctest julia` -- probably a formatting error in the input

**Comment by gkappler** [comment]
Thanks for letting me know, I fixed your issues and some more in the doc.

**Comment by gkappler** [comment]
Thanks again for your improvements, I will close the issue.
