### ISSUE TITLE
`join` `Repeat` parser result in no repetition.

### ISSUE THREAD

**Issue by chengchingwen** [gkappler/CombinedParsers.jl#25]
The `join` function seems to remove the `Repeat` part. For example, the code in the docs `parse(join(Repeat(AnyChar()),','),"a,b,c")` cannot parse string like `"abc,b,c"`

**Comment by gkappler** [comment]
Thanks for your feedback.
At the time I chose this behaviour because `result_type(Repeat(p)) == Vector{result_type(p)}`, and julia's `join` function concatenates elements in such a `Vector` with interleaving the 2nd arg.

To get your desired behavior you would need to write `parse(join(Repeat(Repeat(AnyChar())),','),"abc,b,c")`.

Now, it seems like too complicated thinking. (Especially since I allowed for omitting the Repeat in a later stage).
I am preparing a new version and might deprecate the current behavior such that your expectation is reflected.

However this will likely be a breaking change for some parsers.
Any ideas how to alleviate that?

**Comment by chengchingwen** [comment]
I'm currently writing `Repeat(AnyChar()) * Repeat(',' * Repeat(AnyChar()))` or `Repeat((Repeat(AnyChar()) * ',')) * Repeat(AnyChar())` manually for this kind of parser. I don't know the internal design of CombinedParsers.jl but originally I thought `join` is just a convenient way to write `Repeat(AnyChar()) * Repeat(',' * Repeat(AnyChar()))`. 

> Any ideas how to alleviate that?

I think the usual way is to have people restrict the version to the one before the deprecation happen, but if we really want the backward compatibility, maybe just add a new separate API for this behavior?

**Comment by gkappler** [comment]
The grammar in both examples is identical, but `join` provides a transformation for `Vector{T}` result type, that also removes the separator.
```julia
julia> Repeat(AnyChar()) * Repeat(',' * Repeat(AnyChar()))
🗄 Sequence
├─ .* AnyChar |> Repeat
└─ 🗄* Sequence |> Repeat
   ├─ , 
   └─ .* AnyChar |> Repeat
::Tuple{Array{Char,1},Array{Tuple{Char,Array{Char,1}},1}}


julia> join(Repeat(Repeat(AnyChar())),',')
🗄 Sequence |> map(#63)
├─ .* AnyChar |> Repeat
└─ 🗄* Sequence |> map(#44) |> Repeat
   ├─ , 
   └─ .* AnyChar |> Repeat
::Array{Array{Char,1},1}
```

Also, you might want to use `!` for transforming `Repeat(AnyChar())` to a `SubString` or `!!` to an interned String -- then `join` does not strip the `Repeat` from within the `Transformation` and you can write more briefly:
```julia

julia> join(!Repeat(AnyChar()),',')
🗄 Sequence |> map(#63)
├─ .* AnyChar |> Repeat |> !
└─ 🗄* Sequence |> map(#44) |> Repeat
   ├─ , 
   └─ .* AnyChar |> Repeat |> !
::Array{SubString,1}


julia> join(!!Repeat(AnyChar()),',')
🗄 Sequence |> map(#63)
├─ .* AnyChar |> Repeat |> !!
└─ 🗄* Sequence |> map(#44) |> Repeat
   ├─ , 
   └─ .* AnyChar |> Repeat |> !!
::Array{String,1}
```
Another idea is whether you want to replace `AnyChar()` with `CharNotIn(',')`

```julia
julia> parse_all(join(Repeat(!Repeat(AnyChar())),',')*AtEnd(), "ab,c,d,") |> collect
8-element Array{Tuple{Array{SubString,1},AtEnd},1}:
 (["ab,c,d,"], re"$")
 (["ab,c,d", ""], re"$")
 (["ab,c", "d,"], re"$")
 (["ab,c", "d", ""], re"$")
 (["ab", "c,d,"], re"$")
 (["ab", "c,d", ""], re"$")
 (["ab", "c", "d,"], re"$")
 (["ab", "c", "d", ""], re"$")

julia> parse_all(join(Repeat(!Repeat(CharNotIn(','))),',')*AtEnd(), "ab,c,d,") |> collect
1-element Array{Tuple{Array{SubString,1},AtEnd},1}:
 (["ab", "c", "d", ""], re"$")
```

**Comment by chengchingwen** [comment]
I see. Thanks!
