### ISSUE TITLE
`ParserCombinator.Delayed` equivalent?

### ISSUE THREAD

**Issue by chengchingwen** [gkappler/CombinedParsers.jl#26]
There is a `Delayed` type in ParserCombinator.jl  which allow us to define a loop in the grammar. What do we use in CombinedParser to achieve the same functionality?

**Comment by gkappler** [comment]
You can use `Either` or `@syntax`, see e.g. similar to [ParserCombinator arithmetics](https://juliahub.com/docs/ParserCombinator/CarUQ/2.0.0/) in [CombinedParser arithmetics example](https://gkappler.github.io/CombinedParsers.jl/dev/man/example-arithmetics/) or the [json example in docs](https://gkappler.github.io/CombinedParsers.jl/dev/man/json/).

**Comment by chengchingwen** [comment]
@gkappler Thanks, I also have some questions about the syntax macro posted in #21. Could you take a look at them?
