### ISSUE TITLE
Parsing binary formats

### ISSUE THREAD

**Issue by rick2047** [gkappler/CombinedParsers.jl#4]
Is there a way to use this to parse binary based formats (similar to BSON or MsgPack?).  From what I understand it seems like this library works only on purely text format, can't find a way to make a parser which takes in bytes/uint8

**Comment by gkappler** [comment]
That is possible. I spent some time with bson, will finish testing and provide it as an example in the manual for parsing Vector{UInt8}.  [https://github.com/JuliaIO/BSON.jl](BSON.jl) is probably more optimized though.

**Comment by gkappler** [comment]
I just provided a bson Vector{UInt8} example in the [documentation](https://gkappler.github.io/CombinedParsers.jl/dev/man/bson/).
To work with binary data please update to CombinedParsers 0.1.2, as I removed some type restrictions.

**Comment by rick2047** [comment]
This seems like something I can look into. Thanks a lot. I will close the issue.
