### ISSUE TITLE
Repeat_stop and Repeat_until are taking default Repeat_max values

### ISSUE THREAD

**Issue by rick2047** [gkappler/CombinedParsers.jl#6]
When parsing data with Repeat_stop and Repeat_until, CombinedParsers gives up after 10^6 repeats. Parsing is aborted after that, even if more data is left. For example,

```
dat = [repeat([UInt8(0x61)],10^6+10)...,UInt8(0x62)];
p = Repeat_stop(byte, CharIn(UInt8(0x62)))
parse(p,dat)
1000000-element Array{UInt8,1}:
 0x61
 0x61
 0x61
 0x61
 0x61
 0x61
 0x61
 0x61
 0x61
 0x61
    ⋮
 0x61
 0x61
 0x61
 0x61
 0x61
 0x61
 0x61
 0x61
 0x61
 0x61
```
As you can see it only saw the first 10^6 values and then gave up.

To my understanding the problem is caused because of when declaring Repeat_stop([L1389](https://github.com/gkappler/CombinedParsers.jl/blob/559c6bed0e2c7013ceee69946c6eae09403d6ac2/src/CombinedParsers.jl#L1389)) the arguments are just passed to Repeat() which causes it to take default max=Repeat_max which is 10^6. I propose we just expose the optional arguments to Repeat_stop and Repeat_until and that should just solve the problem. If you agree then I can make a pull request.

**Comment by gkappler** [comment]
Yes, exposing the max as an optional arg in Repeat_stop and Repeat_until seems most general. Please go ahead and thanks for creating a PR! 
The min argument is probably less used, but I think exposing it too is best.

**Comment by gkappler** [comment]
Thanks for the PR. I merged and thus close this issue.
